- hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_common_args: -o ForwardAgent=yes
    repo: git@github.com:bocoup/api.git
  tasks:
    - name: ensure git is installed
      apt:
        name: git
        update_cache: yes
        
    - name: ensure github.com is a known host
      lineinfile:
        dest: /etc/ssh/ssh_known_hosts
        state: present
        create: yes
        regexp: "^github\\.com"
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"

    - name: ensure ssh agent socket environment variable persists when sudoing
      lineinfile:
        dest: /etc/sudoers
        state: present
        insertafter: "^Defaults"
        line: "Defaults\tenv_keep += \"SSH_AUTH_SOCK\""
        validate: "visudo -cf %s"

    - name: check out a private repo as yourself
      git:
        repo: "{{repo}}"
        dest: /mnt
